baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Home'
theme = 'ananke'

[menus]
  [[menus.main]]
    name = 'About'
    pageRef = '/About/index.md'
    weight = 10
  [[menus.main]]
    name = 'Blogs'
    pageRef = '/Blogs/index.md'
    weight = 30
  [[menus.main]]
    name = 'Projects'
    pageRef = '/myProjects'
    weight = 40
  [[menus.main]]
    name = 'Resume'
    url = '/About/Resume.pdf'
    weight = 50